import type { NextPage } from 'next';
import axios from 'axios';
import Head from 'next/head'
import TextField from '@mui/material/TextField';
import styles from '../styles/Home.module.css'
import { Button, Typography } from '@mui/material';
import { useState } from 'react';

const Home: NextPage = () => {
  const [title, setTitle] = useState<string>("");
  const [artist, setArtist] = useState<string>("");
  const [lyrics, setLyrics] = useState<string>("");
  const handleSubmit = async (e: any) => {
    e.preventDefault();
    if (title && artist) {
      const res = await axios.post<any>('/api/getLyrics', {
        data: {
          title,
          artist
        }
      })
      setLyrics(res.data.lyrics);
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.box}>
        <Typography variant="h5" component="h5" className={styles.heading}>
          Search Lyrics
        </Typography>
        <form onSubmit={handleSubmit} className={styles.form}>
          <TextField id="filled-basic" label="Song Title" variant="filled" required={true} className={styles.textFilled} value={title} onChange={(e) => { setTitle(e.target.value) }} />
          <TextField id="filled-basic" label="Filled" variant="filled" required={true} className={styles.textFilled} value={artist} onChange={(e) => { setArtist(e.target.value) }} />
          <Button variant="contained" type="submit" className={styles.button}>Get Lyrics</Button>
        </form>
      </div>
      <div className={styles.lyrics}>
        <p>{
          lyrics ? lyrics : "no lyrics"
        }</p>
      </div>
    </div>
  )
}

export default Home
